title: My blog
author: Yuri A. Parsons
email: yuri@ninjakitty.net
description: > # this means to ignore newlines until "baseurl:"
  Random blog about automation and stuff

# social links
twitter_username: ninjakttty # DO NOT include the @ character, or else the build will fail!
github_username: ninjakttty # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
# theme: minima
# theme: jekyll-theme-modernist
# theme: jekyll-theme-minimal
